export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const JOIN_CHANNEL_REQUEST = 'JOIN_CHANNEL_REQUEST';
export const JOIN_CHANNEL_SUCCESS = 'JOIN_CHANNEL_SUCCESS';

export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST';
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const RESET_CREATE_CHANNEL = 'RESET_CREATE_CHANNEL';

export const GET_CHANNELS_REQUEST = 'GET_CHANNELS_REQUEST';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';

export const CHANNEL_MEMBER_REQUEST = 'CHANNEL_MEMBER_REQUEST';
export const CHANNEL_MEMBER_SUCCESS = 'CHANNEL_MEMBER_SUCCESS';

export const SAVE_CHAT_MESSAGES_REQUEST = 'SAVE_CHAT_MESSAGES_REQUEST';
export const SAVE_CHAT_MESSAGES_SUCCESS = 'SAVE_CHAT_MESSAGES_SUCCESS';

export const GET_CHAT_MESSAGES_REQUEST = 'GET_CHAT_MESSAGES_REQUEST';
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
