export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const JOIN_CHANNEL_REQUEST = 'JOIN_CHANNEL_REQUEST';
export const JOIN_CHANNEL_SUCCESS = 'JOIN_CHANNEL_SUCCESS';

export const CHANNEL_MEMBER_REQUEST = 'CHANNEL_MEMBER_REQUEST';
export const CHANNEL_MEMBER_SUCCESS = 'CHANNEL_MEMBER_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SOCIAL_USER = 'SOCIAL_USER';
